import { CourseTableColumn } from "../definitions/course";

export const courseTableMockData: CourseTableColumn[] = [
  {
    courseCode: 344,
    courseName: "Design and Analysis of Computer Algorithms",
    credits: 4,
    difficulty: 8,
    workload: 9.4,
    overall: 8.3,
    totalReviews: 108,
  },
  {
    courseCode: 352,
    courseName: "Internet Technology",
    credits: 4,
    difficulty: 6.7,
    workload: 5.4,
    overall: 6.2,
    totalReviews: 125,
  },
  {
    courseCode: 405,
    courseName: "Seminar in Computers and Society",
    credits: 4,
    difficulty: 5.3,
    workload: 2.1,
    overall: 8,
    totalReviews: 43,
  },
  {
    courseCode: 411,
    courseName: "Computer Architecture II",
    credits: 4,
    difficulty: 5.3,
    workload: 9,
    overall: 5,
    totalReviews: 304,
  },
  {
    courseCode: 415,
    courseName: "Compilers",
    credits: 4,
    difficulty: 9.3,
    workload: 9,
    overall: 9.3,
    totalReviews: 208,
  },
  {
    courseCode: 417,
    courseName: "Distributed Systems: Concepts and Design",
    credits: 4,
    difficulty: 9,
    workload: 4,
    overall: 7,
    totalReviews: 102,
  },
  {
    courseCode: 419,
    courseName: "Computer Security",
    credits: 3,
    difficulty: 2.2,
    workload: 10,
    overall: 10,
    totalReviews: 192,
  },
];
