import { CourseTableColumn } from "../definitions/course";

export const courseTableMockData: CourseTableColumn[] = [
  {
    subject: "198",
    code: 344,
    name: "Design and Analysis of Computer Algorithms",
    credits: 4,
    difficulty: 8,
    workload: 9.4,
    overall: 8.3,
    totalReviews: 108,
  },
  {
    subject: "198",
    code: 352,
    name: "Internet Technology",
    credits: 4,
    difficulty: 6.7,
    workload: 5.4,
    overall: 6.2,
    totalReviews: 125,
  },
  {
    subject: "198",
    code: 405,
    name: "Seminar in Computers and Society",
    credits: 4,
    difficulty: 5.3,
    workload: 2.1,
    overall: 8,
    totalReviews: 43,
  },
  {
    subject: "198",
    code: 411,
    name: "Computer Architecture II",
    credits: 4,
    difficulty: 5.3,
    workload: 9,
    overall: 5,
    totalReviews: 304,
  },
  {
    subject: "198",
    code: 415,
    name: "Compilers",
    credits: 4,
    difficulty: 9.3,
    workload: 9,
    overall: 9.3,
    totalReviews: 208,
  },
  {
    subject: "198",
    code: 417,
    name: "Distributed Systems: Concepts and Design",
    credits: 4,
    difficulty: 9,
    workload: 4,
    overall: 7,
    totalReviews: 102,
  },
  {
    subject: "198",
    code: 419,
    name: "Computer Security",
    credits: 3,
    difficulty: 2.2,
    workload: 10,
    overall: 10,
    totalReviews: 192,
  },
];
