import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import Nav from "@/components/nav/nav";
import "@/app/globals.css";
import Footer from "@/components/footer/footer";

const font = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex flex-col place-items-center min-h-screen bg-zinc-900">
          <Nav />
          <main className="flex-grow w-full max-w-screen-2xl p-4">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
