import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import Nav from "@/components/nav/nav";
import "@/app/globals.css";

const font = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="min-h-screen w-full bg-zinc-900">
          <Nav />
          <div className="max-w-8xl mx-auto px-4 sm:px-6 md:px-8 pt-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
