import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import Nav from "@/components/nav/nav";
import "@/app/globals.css";

const font = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="flex flex-col place-items-center min-h-screen w-full bg-zinc-900">
          <Nav />
          <div className="w-full max-w-screen-2xl pt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
