export type Review = {
  id: number;
  userId: number;
  semester: number;
  year: number;
  courseCode: number;
  title: string;
  content: string;
  createdAt: Date;
  lastModified: Date;
  upvotes: number;
  downvotes: number;
  difficultyRating: number;
  professorId?: number;
  professorQualityRating?: number;
  professorDifficultyRating?: number;
  lectureRating?: number;
  bookRating?: number;
  piazzaRating?: number;
  workload?: number;
};
